[versions]
java = "17"
okhttp = "4.12.0"
jackson = "2.17.2"
junit = "5.11.0"
coroutines = "1.8.1"

[libraries]
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

jackson-core        = { module = "com.fasterxml.jackson.core:jackson-core",        version.ref = "jackson" }
jackson-databind    = { module = "com.fasterxml.jackson.core:jackson-databind",    version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-jsr310      = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
